baseurl = "/"
languageCode = "en-us"
theme = "hyde"
paginate = 5

[params.twitter]
  creator = "Hubert Mjalski"
  site = "www.hmijalski.com"
  defaultTheme = "light"
  homeSubtitle = "Everything .NET Blog"
  mainSections = ["posts"]
  showReadMore = true
  description = "Everything .NET Blog"


[params]
    description = "Curious .NET developer"

[languages]
  [languages.en]
    languageName = "English"
    title = "Hubert Mijalski"
    descrtiption = "Curious .NET developer"
    owner = ""
    keywords = ""
    copyright = "© 2021 Hubert Mijalski"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Hubert Mijalski .NET Blog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"